name: bayam
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: 3.2.3
  country_picker: 2.0.21
  flutter_screenutil: 5.9.0
  flutter_spinkit: 5.2.0
  flutter_svg: 1.1.6
  image_cropper: 5.0.0
  image_picker: 1.0.4
  package_info_plus: 4.1.0
  permission_handler: 11.0.0
  provider: 6.0.5
  share_plus: 7.1.0
  shared_preferences: 2.2.1
  smooth_page_indicator: 1.1.0
  intl: 0.18.1
  lottie: 2.6.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 1.1.0
  sweet_cookie_jar:
    git:
      url: https://github.com/OssMess/sweet-cookie-jar.git
      ref: 03f728e
  badges: 3.1.2
  country_code_picker: 3.0.0
  phone_number: 1.0.0
  pin_code_fields: 8.0.1
  persistent_bottom_nav_bar: #^5.0.2
    git:
      url: https://github.com/OssMess/PersistentBottomNavBar.git
      ref: 592077c
  emoji_picker_flutter: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  flutter pub run change_app_package_name:main com.example.app
  change_app_package_name: 1.1.0
  # flutter pub run flutter_launcher_icons
  flutter_launcher_icons: 0.13.0
  flutter_lints: 2.0.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/lotties/
  
  fonts:
    - family: AwesomeIcons
      fonts:
        - asset: assets/fonts/AwesomeIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100